version: '3'
services:
    api:
        build: 
            dockerfile: Dockerfile
            context: ./api
        volumes:
            - /app/node_modules
            - ./api:/app
    frontend:
        stdin_open: true
        build: 
            dockerfile: Dockerfile
            context: ./frontend
        volumes:
            - /app/node_modules
            - ./frontend:/app
    nginx:
        depends_on:
        - api
        - frontend
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports:
            - '4080:80'