version: '3'
services:
    front:
        stdin_open: true
        build: 
            dockerfile: Dockerfile.dev
            context: ./frontend
        volumes:
            - /app/node_modules
            - ./frontend:/app
    nginx:
        depends_on:
        - front
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '4080:80'