version: '3'
services:
    api:
        build: 
            dockerfile: Dockerfile.dev
            context: ./identidad-digital-api
        volumes:
            - /app/node_modules
            - ./identidad-digital-api:/app
    frontend:
        stdin_open: true
        build: 
            dockerfile: Dockerfile.dev
            context: ./identidad-digital-frontend
        volumes:
            - /app/node_modules
            - ./identidad-digital-frontend:/app
    nginx:
        depends_on:
        - api
        - frontend
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '4080:80'